$content = Get-Content -Path "d:\تطبيقات\تطبيق قائمة الكتب 2\main.js" -Raw

$content = [regex]::Replace($content, "(?ms)(chosenBooks = \{\};\s*\n\s*\}\s*\n\s*)(\} catch \(e\) \{)", "`$1        // Load requestedBooks`n        let requestedBooksString = localStorage.getItem('bookAppData_requestedBooks');`n        if (!requestedBooksString) {`n          try {`n            requestedBooksString = sessionStorage.getItem('bookAppData_requestedBooks');`n          } catch (sessionError) {}`n        }`n        if (requestedBooksString) {`n          const requestedBooksData = JSON.parse(requestedBooksString);`n          if (requestedBooksData.requestedBooks) {`n            requestedBooks = requestedBooksData.requestedBooks;`n            if (typeof window.updateRequestedBooksBadge === 'function') {`n              window.updateRequestedBooksBadge();`n            }`n          }`n        }`n      `$2")

$content = [regex]::Replace($content, "(?ms)(throw new Error\('لا توجد بيانات مستويات في قاعدة البيانات'\);\s*\}\s*\n\s*)(\} else \{)", "`$1          if (data.requestedBooks) {`n            requestedBooks = data.requestedBooks;`n            localStorage.setItem('bookAppData_requestedBooks', JSON.stringify({ requestedBooks }));`n            if (typeof window.updateRequestedBooksBadge === 'function') {`n              window.updateRequestedBooksBadge();`n            }`n          }`n        `$2")

$content = [regex]::Replace($content, "(?ms)(localStorage\.setItem\('bookAppData_levels', JSON\.stringify\(\{ levels \}\)\);\s*\}\s*\n\s*)(\}\s*\n\n\s*renderLevels\(\);)", "`$1          if (data.requestedBooks) {`n            requestedBooks = data.requestedBooks;`n            localStorage.setItem('bookAppData_requestedBooks', JSON.stringify({ requestedBooks }));`n            if (typeof window.updateRequestedBooksBadge === 'function') {`n              window.updateRequestedBooksBadge();`n            }`n            if (document.getElementById('requestedBooksModal') && document.getElementById('requestedBooksModal').style.display === 'flex') {`n              if (typeof window.renderRequestedBooksList === 'function') {`n                window.renderRequestedBooksList();`n              }`n            }`n          }`n        `$2")

Set-Content -Path "d:\تطبيقات\تطبيق قائمة الكتب 2\main.js" -Value $content -Encoding UTF8
